[package]
name = "is-thirteen-with-wasm"
version = "0.1.2"
authors = ["Erin Moore <erinmoorethefirst@gmail.com>"]
description = "find out if it's 13"
license = "MIT"
repository = "https://github.com/ErinLMoore/hello-wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
