[package]
name = "is-thirteen-with-wasm"
version = "0.1.0"
authors = ["Erin Moore <erin.moore@joinroot.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
